@startuml
    Interface IRakNetSocket {

    }


    class BackGroundService {
        +ExecuteAsync()

        +StartAsync();
        +StopAsync();
    }

    class RakNetHostedService {
        
    }

    RakNetHostedService |... BackGroundService

    IRakNetSocket <--- RakNetHostedService
@enduml